server:
  port: ${PORT:8084}

spring:
  application:
    name: notification-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
